# Generated by Django 3.2.25 on 2024-11-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energydata',
            options={'ordering': ['-date', 'region'], 'verbose_name': 'Donnée Énergétique', 'verbose_name_plural': 'Données Énergétiques'},
        ),
    ]
